# Generated by Django 2.2.1 on 2020-06-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_wasted', models.IntegerField()),
                ('food_prepared', models.IntegerField()),
                ('base_unit', models.CharField(choices=[('pieces', 'pieces'), ('kg', 'kg')], max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_management.Items')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_management.Meal')),
            ],
        ),
    ]
